### ISSUE TITLE
Python module issues on Mac

### ISSUE THREAD

**Issue by jturney** [robparrish/lightspeed#12]
There are several issues in the cmake files dealing with the Python module creation on a Mac. To list a couple:
* Name of the target file.
* Undefined functions from Ambit/BLAS/LAPACK

I'll get these working on my Mac and then confirm on Ubuntu 14.04.

**Comment by jturney** [comment]
@robparrish How do you handle libint on Linux? I'm currently forcing configure to add `-fPIC` as a compiler command line option. The `--with-pic` option didn't work like I was expecting. I tried the `--enable-shared` but either I'm missing packages on my box or it isn't working.

**Comment by robparrish** [comment]
../configure --prefix=/theoryfs2/ds/parrish/libint-1.1.5/install2
--with-pic=yes --enable-shared


-Rob

**Comment by jturney** [comment]
This was resolved by upgrading to libint2 (issue #13) and changes to cmake files in commits 5b6d991 and 5af97b2.
